import { ProcessStageId, StageConfig } from '../types';

export const PROCESS_STAGES: StageConfig[] = [
  {
    id: 'REQUEST_RECEIVED',
    order: 1,
    name: 'Customer Request Received',
    shortName: 'Request',
    category: 'Commercial',
    weightPercent: 2,
    responsibleDepartment: 'Sales',
    description: 'Initial customer inquiry, technical specs, capacity and application requirements',
  },
  {
    id: 'QUESTION_RECEIVED',
    order: 2,
    name: 'Question / Clarification Received',
    shortName: 'Clarifications',
    category: 'Technical',
    weightPercent: 3,
    responsibleDepartment: 'Technical',
    description: 'Technical, commercial, utility, and site clarifications with customer',
  },
  {
    id: 'TECHNICAL_COMPREHENSION',
    order: 3,
    name: 'Technical Comprehension & Feasibility',
    shortName: 'Technical Study',
    category: 'Technical',
    weightPercent: 5,
    responsibleDepartment: 'Technical',
    description: 'Requirement study, engineering feasibility, utility review & solution design',
  },
  {
    id: 'QUOTATION_RECEIVED',
    order: 4,
    name: 'Quotation Received & Prepared',
    shortName: 'Quotation',
    category: 'Commercial',
    weightPercent: 5,
    responsibleDepartment: 'Commercial',
    description: 'Detailed price breakup, commercial offer, revisions (Rev 0, 1, 2) & terms',
  },
  {
    id: 'COMMERCIAL_NEGOTIATION',
    order: 5,
    name: 'Commercial Negotiation',
    shortName: 'Negotiation',
    category: 'Commercial',
    weightPercent: 5,
    responsibleDepartment: 'Commercial',
    description: 'Discount review, commercial meeting logs, final terms & payment agreements',
  },
  {
    id: 'APPROVAL',
    order: 6,
    name: 'PO & Commercial Approval',
    shortName: 'PO Approval',
    category: 'Commercial',
    weightPercent: 5,
    responsibleDepartment: 'Management',
    description: 'Management authorization of customer PO & commercial terms. Rejection routes back.',
  },
  {
    id: 'WORK_ORDER',
    order: 7,
    name: 'Work Order Done',
    shortName: 'Work Order',
    category: 'Manufacturing',
    weightPercent: 5,
    responsibleDepartment: 'Production',
    description: 'Internal work order generation, BOM finalization, planning & supplier check',
  },
  {
    id: 'ADVANCE_PAYMENT',
    order: 8,
    name: 'Advance Payment Received',
    shortName: 'Advance Pay',
    category: 'Commercial',
    weightPercent: 5,
    responsibleDepartment: 'Accounts',
    description: 'Advance milestone collection, invoice tracking, LC / BG verification',
  },
  {
    id: 'MANUFACTURING',
    order: 9,
    name: 'Manufacturing In Progress',
    shortName: 'Manufacturing',
    category: 'Manufacturing',
    weightPercent: 25,
    responsibleDepartment: 'Production',
    description: 'Procurement, fabrication, machining, assembly, and stage-wise QC testing',
  },
  {
    id: 'READY_FOR_DISPATCH',
    order: 10,
    name: 'Ready for Dispatch',
    shortName: 'Dispatch Ready',
    category: 'Manufacturing',
    weightPercent: 5,
    responsibleDepartment: 'Quality',
    description: 'Final inspection, packaging, gross/net weight certification & dispatch clearance',
  },
  {
    id: 'DELIVERY_SCHEDULED',
    order: 11,
    name: 'Delivery Scheduled & In Transit',
    shortName: 'Transit',
    category: 'Manufacturing',
    weightPercent: 5,
    responsibleDepartment: 'Logistics',
    description: 'Transporter logistics, vehicle & LR tracking, site arrival confirmation',
  },
  {
    id: 'SITE_READINESS',
    order: 12,
    name: 'Site Readiness Assessment',
    shortName: 'Site Readiness',
    category: 'Site',
    weightPercent: 5,
    responsibleDepartment: 'Project',
    description: 'Civil, Electrical & Mechanical checklists, Site Readiness Certificate & Decision',
  },
  {
    id: 'MATERIAL_RECEIVED',
    order: 13,
    name: 'Material Received at Site',
    shortName: 'GRN / Unload',
    category: 'Site',
    weightPercent: 3,
    responsibleDepartment: 'Project',
    description: 'Physical GRN inspection at client site, shortage/damage checking & storage',
  },
  {
    id: 'INSTALLATION_ERECTION',
    order: 14,
    name: 'Installation & Erection',
    shortName: 'Installation',
    category: 'Site',
    weightPercent: 10,
    responsibleDepartment: 'Mechanical',
    description: 'Level-by-level Civil finishing, Electrical wiring, and Mechanical alignment',
  },
  {
    id: 'WORK_PROGRESS',
    order: 15,
    name: 'Work Progress Tracking',
    shortName: 'Daily Progress',
    category: 'Site',
    weightPercent: 3,
    responsibleDepartment: 'Project',
    description: 'Daily progress logs, manpower count, bottlenecks, photo evidence & pending triage',
  },
  {
    id: 'PRE_COMMISSIONING',
    order: 16,
    name: 'Pre-Commissioning Checks',
    shortName: 'Pre-Comm',
    category: 'Site',
    weightPercent: 3,
    responsibleDepartment: 'Electrical',
    description: 'Mandatory mechanical, electrical, instrument & safety interlock validations',
  },
  {
    id: 'COMMISSIONING',
    order: 17,
    name: 'Commissioning & Machine Start',
    shortName: 'Commissioning',
    category: 'Site',
    weightPercent: 3,
    responsibleDepartment: 'Service',
    description: 'Trial runs, parameter calibrations, performance test & customer signoff',
  },
  {
    id: 'MACHINE_START',
    order: 18,
    name: 'Machine Start Date Confirmation',
    shortName: 'Machine Start',
    category: 'Handover',
    weightPercent: 2,
    responsibleDepartment: 'Management',
    description: 'Official commercial production start timestamp & project handover milestone',
  },
  {
    id: 'DOCUMENTATION_HANDOVER',
    order: 19,
    name: 'Documentation & Handover',
    shortName: 'Documentation',
    category: 'Handover',
    weightPercent: 3,
    responsibleDepartment: 'Technical',
    description: 'O&M manuals, warranty certificates, as-built electrical/mechanical drawings',
  },
  {
    id: 'FINAL_PAYMENT',
    order: 20,
    name: 'Final Payment Clearance',
    shortName: 'Final Payment',
    category: 'Commercial',
    weightPercent: 3,
    responsibleDepartment: 'Accounts',
    description: 'Final invoice settlement, dues reconciliation & retention release',
  },
  {
    id: 'AFTER_SALES_SERVICE',
    order: 21,
    name: 'After Sales Service & Warranty',
    shortName: 'After Sales',
    category: 'Service',
    weightPercent: 0, // ongoing lifecycle monitoring
    responsibleDepartment: 'Service',
    description: 'Warranty tracking, AMC contracts, preventive maintenance & service tickets',
  },
];

export const STAGE_MAP = new Map<ProcessStageId, StageConfig>(
  PROCESS_STAGES.map((s) => [s.id, s])
);

export function getStageOrder(id: ProcessStageId): number {
  return STAGE_MAP.get(id)?.order ?? 1;
}

export function getNextStageId(current: ProcessStageId): ProcessStageId | null {
  const currentOrder = getStageOrder(current);
  const next = PROCESS_STAGES.find((s) => s.order === currentOrder + 1);
  return next ? next.id : null;
}
